name: Update Docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: synfinatic/mkdocs-deploy-gh-pages@bump-mkdocs
        # mhausenblas/mkdocs-deploy-gh-pages@master is an old version of mkdocs, so using my own
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # CUSTOM_DOMAIN: optionaldomain.com
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: mkdocs-asciinema
          # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: docs/requirements.txt
